### PR TITLE
release: v1.1.0

### PR DESCRIPTION
**Pull request by drjova**
Signed-off-by: Harris Tzovanakis <me@drjova.com>

### CODE REVIEW

**Comment by lnielsen** [comment]
I think this should likely go as ``1.1.0`` instead as we're changing package dependency. I.e. any env already created will have the ``msgpack-python`` package installed. If you install ``msgpack`` on top, then I think it will correctly overwrite the other python module (i.e. ``import msgpack`` will work fine). However, if you do ``pip freeze`` you'll have both packages that look like they are installed.

I would add to the change log e.g.:

```
Version 1.1.0 (released 2019-06-21):

- Changed the ``msgpack-python`` dependency to ``msgpack``. Please first uninstall ``msgpack-python`` before installing the new ``msgpack`` dependency (``pip uninstall msgpack-python``).
```

**Comment by drjova** [comment]
@lnielsen updated, thank you :)

**Comment by lnielsen** [comment]
Sorry, just seeing this one now

**Comment by drjova** [comment]
thank you

**Pull request merged**
